version: '3.1'
services:
  codrr_pg:
    image: postgres:latest
    container_name: codrr_pg
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=hola123
      - POSTGRES_DB=codrr_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432